# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Acme-Terror-UK
version:      0.02
version_from: lib/Acme/Terror/UK.pm
installdirs:  site
requires:
    LWP::Simple:                   1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
