--- #YAML:1.0
name:               Acme-Terror-UK
version:            0.06
abstract:           Fetch the current UK terror alert level
author:
    - A. U. Thor <pricer@localdomain>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    LWP::Simple:  5.48
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
